version: 0.0
os: linux
files:
  - source: ./
    destination: /DpyApp/new_chatapp/
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 600
      runas: root

